export const FIELD_STATES = Object.freeze([
  'KNOWN_VALUE',
  'EXPLICIT_NONE',
  'NOT_APPLICABLE',
  'UNKNOWN',
  'UNCERTAIN',
  'CONFLICT',
  'INVALID',
  'INFERRED',
]);

export const SUPPORT_TYPES = Object.freeze([
  'TRANSCRIPT_EVIDENCE',
  'AUTHORITATIVE_SYSTEM_DATA',
  'DOCUMENT_EVIDENCE',
  'MANUAL_TECHNICIAN_INPUT',
  'TECHNICIAN_CONFIRMATION',
  'AI_INFERENCE',
  'RAG_GUIDANCE',
]);

export const SESSION_PHASES = Object.freeze([
  'CONTEXT',
  'CAPTURE',
  'PROCESSING',
  'CORRECTION_IF_NEEDED',
  'RESOLVE',
  'REVIEW',
  'READY',
  'CONFIRMED',
  'RECOVERABLE_ERROR',
]);
